// Chamber visual + atmosphere config (frontend mirror of backend personas)
export const CHAMBER_THEME = {
  senate: {
    id: "senate",
    name: "The Senate",
    short: "Senate",
    biology: "Frontal Lobe",
    domain: "Power, governance, public life",
    primary: "#8B1A1A",
    accent: "#C9A961",
    glowRgba: "rgba(201, 169, 97, 0.35)",
    atmosphere: "texture_marble",
    blendMode: "screen",
    opacity: 0.18,
  },
  boardroom: {
    id: "boardroom",
    name: "The Boardroom",
    short: "Boardroom",
    biology: "Parietal Lobe",
    domain: "Enterprise, stewardship, money",
    primary: "#0F4F3F",
    accent: "#B8864F",
    glowRgba: "rgba(184, 134, 79, 0.30)",
    atmosphere: "texture_marble",
    blendMode: "soft-light",
    opacity: 0.16,
  },
  courtroom: {
    id: "courtroom",
    name: "The Court Room",
    short: "Court Room",
    biology: "Temporal Lobe",
    domain: "Family, covenant, kinship",
    primary: "#3A2419",
    accent: "#A88A4A",
    glowRgba: "rgba(168, 138, 74, 0.30)",
    atmosphere: "texture_parchment",
    blendMode: "soft-light",
    opacity: 0.14,
  },
  council: {
    id: "council",
    name: "The Council",
    short: "Council",
    biology: "Occipital Lobe",
    domain: "Faith, conscience, ultimate things",
    primary: "#1B2A5C",
    accent: "#F5F2EC",
    glowRgba: "rgba(245, 242, 236, 0.28)",
    atmosphere: "texture_cathedral",
    blendMode: "soft-light",
    opacity: 0.20,
  },
  forge: {
    id: "forge",
    name: "The Forge",
    short: "Forge",
    biology: "Corpus Callosum",
    domain: "The unclassified, the tangled",
    primary: "#C84A1F",
    accent: "#FFE5B4",
    glowRgba: "rgba(255, 229, 180, 0.55)",
    atmosphere: "texture_forge",
    blendMode: "screen",
    opacity: 0.32,
  },
};

export const CHAMBER_ORDER = ["senate", "boardroom", "courtroom", "council", "forge"];
